GET http://localhost:3000/places?text=av marechal castelo branco, contagem

###
GET http://localhost:3000/places?text=av amazonas, belo horizonte

###
@originId = ChIJ-2HK4--VpgARkp0CWi5Nc7o

@destinationId = ChIJXWMaVg-XpgARhwSUfrM5iwM

###
GET http://localhost:3000/directions?originId={{originId}}&destinationId={{destinationId}}


###
POST http://localhost:3000/routes
Content-Type: application/json
  
  {
    "name": "Rota 1",
    "source_id": "ChIJ-2HK4--VpgARkp0CWi5Nc7o",
    "destination_id": "ChIJXWMaVg-XpgARhwSUfrM5iwM"
  }

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/675a301ba9d917d7ce783bad